name: Deploy MMO on production server

# Controls when the action will run. Triggers the workflow on push or pull request events against any branch (the workflow will only (re)deploy the latest tag though)
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    # (Re)deploys the latest release on the remote host
    - name: Stop the currently running server
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          tmux kill-session -t gameserver
          cd ${{ secrets.REMOTE_GAME_DIR }}
          git fetch --tags
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $latestTag
          source ${{ secrets.REMOTE_GAME_DIR }}/server/venv/activate
          python ${{ secrets.REMOTE_GAME_DIR }}/server/manage.py makemigrations server
          python ${{ secrets.REMOTE_GAME_DIR }}/server/manage.py migrate
          tmux new-session -d -s gameserver \; send-keys "python ${{ secrets.REMOTE_GAME_DIR }}/server" Enter
          exit
